### ISSUE TITLE
Bank Bonus Page

### ISSUE THREAD

**Issue by jennweems** [ohiosveryown/atldeals#2]
Only allows 3 posts (at on the bank bonus page, older posts do not show up on the page

**Comment by jennweems** [comment]
Can the post title on the other pages (such as bank bonus and credit card) be the post title and not the description?

**Comment by ohiosveryown** [comment]
> Only allows 3 posts (at on the bank bonus page, older posts do not show up on the page

This should be fixed. I added bank-bonus tags to two placeholder posts and [it looks like it's working now](https://atl.deals/bank-bonus).

> Can the post title on the other pages (such as bank bonus and credit card) be the post title and not the description?

Yeah, this will be a little more work but definitely do-able. Opening a new issue for that and closing this one.
