### ISSUE TITLE
Card width is variable based on content

### ISSUE THREAD

**Issue by jennweems** [ohiosveryown/atldeals#3]
Can you make the dimensions of the cards fixed? Dimensions of the boxes on the home page get bigger or smaller depending on the text.

**Comment by jennweems** [comment]
If not its fine. I can just make sure every description is long enough

**Comment by ohiosveryown** [comment]
@jennweems yeah this is a simple fix – _note to self (be sure to test at different breakpoints):_
- .card { @include breakpoint(md) { min-width: 50%; }}

**Comment by ohiosveryown** [comment]
Updated:
https://github.com/ohiosveryown/atldeals/commit/24b3e3940e1948abcda7f3c69977b2e2a15e79cb
