### ISSUE TITLE
Mobile View Menu Dropdown

### ISSUE THREAD

**Issue by jennweems** [ohiosveryown/atldeals#4]
On the mobile view, Freebies and The Blog are indented on the drop down

**Comment by ohiosveryown** [comment]
@jennweems, this is a simple fix.
_note to self:_ increase opacity for nav background (chrome doesn't blur bg contents like safari.)
<img width="200" alt="screen shot 2018-10-24 at 10 41 24 am" src="https://user-images.githubusercontent.com/12748054/47438998-8e1bc780-d779-11e8-922b-acc949ace58e.png">
<img width="200" alt="screen shot 2018-10-24 at 10 42 20 am" src="https://user-images.githubusercontent.com/12748054/47438999-8e1bc780-d779-11e8-8575-b6d635e5d5f7.png">

**Comment by ohiosveryown** [comment]
Fixed the indentation.
