### ISSUE TITLE
Deals not showing up on home page (only freebies)

### ISSUE THREAD

**Issue by jennweems** [ohiosveryown/atldeals#5]
In the deals & freebies section, only the freebies are showing up

**Comment by ohiosveryown** [comment]
This is intended for the current design. If you want the deals to surface on the home page, rather than just through the nav, I'll have to know how you want them laid out.

**Comment by jennweems** [comment]
Can the you add them with the freebies section? So its freebies and deals in the same section on the home page.

**Comment by ohiosveryown** [comment]
Updated:
https://github.com/ohiosveryown/atldeals/commit/f383f3a0a0f6ed10aa057ae51a27f21307adf0d6
