### ISSUE TITLE
Update Card Background(s)

### ISSUE THREAD

**Issue by ohiosveryown** [ohiosveryown/atldeals#7]
@jennweems can you link to the one or two images for the card backgrounds here.

**Comment by jennweems** [comment]
![cash-money-bills-on-woodgrain_4460x4460](https://user-images.githubusercontent.com/43557128/47590051-12687900-d939-11e8-81ec-e671e319224b.jpg)

**Comment by jennweems** [comment]
I honestly really like the ones that are on there now.
